export const shorthands = {
	bg: ['background'],
	b: ['border'],
	bt: ['borderTop'],
	br: ['borderRight'],
	bb: ['borderBottom'],
	bl: ['borderLeft'],
	bx: ['borderLeft', 'borderRight'],
	by: ['borderTop', 'borderBottom'],
	h: ['height'],
	m: ['margin'],
	mt: ['marginTop'],
	mr: ['marginRight'],
	mb: ['marginBottom'],
	ml: ['marginLeft'],
	my: ['marginTop', 'marginBottom'],
	mx: ['marginLeft', 'marginRight'],
	p: ['padding'],
	pt: ['paddingTop'],
	pr: ['paddingRight'],
	pb: ['paddingBottom'],
	pl: ['paddingLeft'],
	py: ['paddingTop', 'paddingBottom'],
	px: ['paddingLeft', 'paddingRight'],
	w: ['width']
};
